"""
Zawiera właściwości gry.
"""

FIELD_SIZE = 80
GAP = 15
BOARD_WIDTH = 7
BOARD_HEIGHT = 6
SCREEN_WIDTH = FIELD_SIZE * BOARD_WIDTH + GAP * (BOARD_WIDTH + 1)
SCREEN_HEIGHT = FIELD_SIZE * BOARD_HEIGHT + GAP * (BOARD_HEIGHT + 1)
FONT_SIZE = 50
ENEMY = 'o'
PLAYER = 'x'
